name:                extensible-sql
version:             0.1.0.0
github:              "githubuser/extensible-sql"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/extensible-sql#readme>

dependencies:
- base >= 4.8 && < 5
- dlist
- extensible
- mtl
- persistent
- safe
- text
- transformers

library:
  source-dirs: src

executables:
  extensible-sql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - extensible-sql
    - persistent-template

tests:
  extensible-sql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit
    - containers
    - extensible-sql
    - hspec == 2.*
    - monad-logger
    - persistent-mysql
    - persistent-postgresql
    - persistent-template
    - resourcet
    - time
